package com.movieexpress.backend.customexception;

public class ErrorCodes {
    public static final int SUCCESS = 200;
    public static final int FAILURE = 400;
    public static final int EMAIL_NOT_FOUND = 401;
    public static final int INVALID_EMAIL_FORMAT = 402;
    public static final int INVALID_PASSWORD = 403;
    public static final int EMPTY_FIELD = 404;
    public static final int USER_ALREADY_EXISTS = 405;
    public static final int USER_NOT_FOUND = 406;
    public static final int ACCESS_DENIED = 407;
    public static final int TOKEN_EXPIRED = 408;
    public static final int TOKEN_INVALID = 409;
    public static final int PASSWORD_TOO_SHORT = 410;
    public static final int PASSWORD_TOO_WEAK = 411;
    public static final int ACCOUNT_DISABLED = 412;
    public static final int AUTHENTICATION_FAILED = 413;
    public static final int AUTHORIZATION_FAILED = 414;
    public static final int SESSION_EXPIRED = 415;
    public static final int SERVER_ERROR = 500;
    public static final int DATABASE_ERROR = 501;
    public static final int EXECUTOR_ERROR = 502;
    public static final int INVALID_INPUT = 503;
    public static final int RESOURCE_NOT_FOUND = 504;
    public static final int UNAUTHORIZED_ACCESS = 505;
    public static final int FORBIDDEN_ACCESS = 506;
    public static final int INVALID_TOKEN = 507;
    public static final int EXPIRED_TOKEN = 508;
    public static final int UNPROCESSABLE_ENTITY = 509;
    public static final int INTERNAL_SERVER_ERROR = 510;
    public static final int NOT_IMPLEMENTED = 511;
    public static final int SERVICE_UNAVAILABLE = 512;
    public static final int BAD_GATEWAY = 513;
    public static final int GATEWAY_TIMEOUT = 514;
    public static final int NETWORK_ERROR = 515;
    public static final int FILE_NOT_FOUND = 516;
    public static final int INVALID_FILE_FORMAT = 517;
    public static final int UNSUPPORTED_OPERATION = 518;
    public static final int TIMEOUT_ERROR = 519;
    public static final int INVALID_REQUEST = 520;
    public static final int UNKNOWN_ERROR = 521;
    public static final int OPERATION_FAILED = 522;
    public static final int LIMIT_EXCEED = 523;
    public static final int INVALID_ID = 524;
    public static final int INVALID_CAPTCHA = 525;
    public static final int INVALID_IP_ADDRESS = 526;
}
